# OCR Toml Config

title = "TTS Service Config"
ENV = "default"

DEBUG = false
SQLALCHEMY_TRACK_MODIFICATIONS = false

# DB
DB_USERNAME = "tts"
DB_PASSWORD = "tts"
DB_HOST = "localhost"
DB_DATABASE = "tts"
DB_PORT = "5432"
#DB_USERNAME = "yqmrsepyqlzcsw"
#DB_PASSWORD = "f01a5d3aed7bedc6717237ab31d2c1b2ac73cbc1159a36ba109b65d8ee5fdc96"
#DB_HOST = "ec2-52-206-38-187.compute-1.amazonaws.com"
#DB_DATABASE = "d9e776m7ret5a1"
#DB_PORT = "5432"
# DB Conn pool config
POOL_PRE_PING = true
POOL_TIMEOUT = 120
POOL_SIZE = 5
MAX_OVERFLOW = 10

#AWS ACCESS KEYS
aws_access_key_id="AKIAW22X43X22B3CSB5J"
aws_secret_access_key="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"
aws_region_name = "us-east-2"
aws_bucket_name = "sagemaker-us-east-2-469946392053"

jwt_expiry_time = 7 # In days
jwt_secret = "vaux-0199-010"